In [1]:
myList = ['pineapple', 'banana', 'watermelon', 'mango']

index = 0
while index < len(myList):
    element = myList[index]
    print(len(element))
    index += 1

9
6
10
5


In [24]:
!python -m pip install numpy

In [25]:
import numpy as np

In [32]:
a=np.array([3,8,2,67,45])

In [39]:
def show_array(arr):
    print('Array:',arr,sep='\n')
    print('type:',type(a))
    print('shape:',a.shape)
    print('size:',a.size)
    print('DType:',arr.dtype)
    print('length:',len(a))
    print('dimension:',a.ndim)

In [59]:
#10 11 13 14
#45 22 9 2
#6 5 1 8
b=np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])
show_array(b)

Array:
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
type: <class 'numpy.ndarray'>
shape: (5,)
size: 5
DType: int32
length: 5
dimension: 1


In [35]:
#array operation
#item accessing:subscripting,slicing
#item assignment
#item insertion
#item deletion
#arithmetic

In [41]:
            #100 110 13 140
            #145 22 9 2
            #16 15 11 18
#10 11 23 14
#45 22 9 2
#6 5 1 8
c=np.array([[[10,100],[11,110],[23,13],[14,140]],
            [[45,145],[22,122],[9,19],[2,12]],
            [[6,16],[5,15],[1,11],[8,18]]])
show_array(c)

Array:
[[[ 10 100]
  [ 11 110]
  [ 23  13]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]
type: <class 'numpy.ndarray'>
shape: (5,)
size: 5
DType: int32
length: 5
dimension: 1


In [43]:
b



array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [51]:
[[10,11,13,14],[45,22,9,2],[6,5,1,8]]
#b[0][0]
#b[1][1:]
#subscripting [1st,2nd,3rd...............,nth dim]
#subscripting [1st:1st end:stepsize,2nd,3rd...............,nth dim]
b[0,0]
b[1,-3:]
b[:,-2]

array([13,  9,  1])

In [53]:
b[:,-2].shape

(3,)

In [58]:
b[:,-2:-1]

array([[13],
       [ 9],
       [ 1]])

In [93]:
print(b[-1:,:])
print(c[:1,:2,:])
print(c[:,1:2,:1])
print(c[-2:-1:,:1])
print(c[:2,-2:,:])



[[6 5 1 8]]
[[[ 10 100]
  [ 11 110]]]
[[[11]]

 [[22]]

 [[ 5]]]
[[[ 45 145]]]
[[[ 23  13]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [94]:
print(b[-1:,:].shape)
print(c[:1,:2,:].shape)
print(c[:,1:2,:1].shape)
print(c[-2:-1:,:1].shape)
print(c[:2,-2:,:].shape)

(1, 4)
(1, 2, 2)
(3, 1, 1)
(1, 1, 2)
(2, 2, 2)


In [95]:
#itemn assignment
b[1,2]=90
b

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [97]:
#item insertion
a=np.append(a,80)
a

array([ 3,  8,  2, 67, 45, 80])

In [112]:
np.append(b, [[9,90,900,9000]], axis = 0)    #axis =0=rows,axis=1=col

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [108]:
np.append(b,[[9,90,900]],axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [115]:
#item deletionn
np.delete(b,0,axis=0)

array([  11,   13,   14,   45,   22,   90,    2,    6,    5,    1,    8,
          9,   90,  900, 9000,    9,   90,  900, 9000])

In [116]:
b-9

array([   1,    2,    4,    5,   36,   13,   81,   -7,   -3,   -4,   -8,
         -1,    0,   81,  891, 8991,    0,   81,  891, 8991])

In [1]:
#array manipulation
#arr.reshape()
#arr.astype()
#more functions to create array
#np.array()
#np.arrange() ->array version of range func,also allows float
#np.linspace() ->start,end,no. of items
#np.ones  ->generate all values as '1'
#np.zeros()  ->generate all values as '0'
#np.random.random()
np.random.randint()
b.reshape(2,6,1,1)



NameError: name 'np' is not defined

In [121]:
b.astype(float)

array([1.0e+01, 1.1e+01, 1.3e+01, 1.4e+01, 4.5e+01, 2.2e+01, 9.0e+01,
       2.0e+00, 6.0e+00, 5.0e+00, 1.0e+00, 8.0e+00, 9.0e+00, 9.0e+01,
       9.0e+02, 9.0e+03, 9.0e+00, 9.0e+01, 9.0e+02, 9.0e+03])

In [126]:
b.astype('uint16')

array([  10,   11,   13,   14,   45,   22,   90,    2,    6,    5,    1,
          8,    9,   90,  900, 9000,    9,   90,  900, 9000], dtype=uint16)